version: '3.7'

services:
  db:
    container_name: rebirth_talk_db
    image: postgres:16.0
    environment:
      POSTGRES_USER: rebirth_talk_user
      POSTGRES_PASSWORD: rebirth_talk_pw
      POSTGRES_DB: rebirth_talk_db
      PGDATA: /data/postgres
    volumes:
      - rebirth_talk_db:/data/postgres
    networks:
      - rebirth_talk_network
    ports:
      - "5449:5432"

  backend:
    container_name: rebirth_talk_backend
    build: ./back
    volumes:
      - ./back:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - rebirth_talk_network
    env_file:
      - ./back/.env

#  redis:
#    image: 'bitnami/redis:6.2.14'
#    container_name: news_redis
#    ports:
#      - "6379:6379"
#    environment:
#      REDIS_PASSWORD: J5EGHdss54rtghjgfEWSDbvtr
#    networks:
#      - rebirth_talk_network

networks:
  rebirth_talk_network:
    driver: bridge

volumes:
  rebirth_talk_db:
